### ISSUE TITLE
Polls

### ISSUE THREAD

**Issue by GamingWithEPMninjaYT** [navi1995/Movie-Night-Discord-Bot#3]
When I started a poll, it ended after one person voted on a movie. Help?

**Comment by navi1995** [comment]
Have you set a larger poll time than 10 seconds? Cannot reproduce this with the most recent code

**Comment by mahousenshi** [comment]
Just to not create a new issue. In a server that i'm interested to add your bot we have polls that take days to close. Its not possible to implement unlimited pool time and implement a "endpoll" command?

**Comment by navi1995** [comment]
@mahousenshi The primary reason currently is because of hosting on AWS servers and the amount of RAM needed for long running commands (causes memory leaks/hikes which I can't really pay for).

If you have experience you could fork the repo and then create a longer maximum time, but I've had to limit it due to the number of servers/RAM usage associated with it.
